-- AlterEnum
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'HOUSE_CLEANING';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'PLUMBING_SERVICES';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'ELECTRICAL_SERVICES';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'GARDEN_CARE';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'POOL_CLEANING_MAINTENANCE';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'CHEF_CATERING';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'WAITERING_SERVICES';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'MOVING_SERVICES';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'AU_PAIR_SERVICES';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'LOCKSMITH_SERVICES';